# Site settings
title: CIS700
baseurl: "program-analysis"
url: "http://kmicinski.com/"
description: "(Fall '19) Program Analysis--Foundations and Applications (CIS700 @ Syracuse U)"
permalink: pretty

# Build settings
#markdown: redcarpet

# Build posts to appear in the future
future: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
